language: cpp

matrix:
  include:
    - name: "Windows"
      os: windows
    - name: "Linux"
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "OSX"
      os: osx

before_script:
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -DCMAKE_GENERATOR_PLATFORM=x64 .. ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. ; fi
  - cmake --build .

branches:
  only:
    - master

notifications:
  email: false

