language: cpp

matrix:
  include:
    - name: "Windows"
      os: windows
    - name: "Linux"
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "Linux arm64"
      os: linux
      arch: arm64
      dist: bionic
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "OSX"
      os: osx

before_script:
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -G "Visual Studio 15 2017 Win64" .. ; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. ; fi
  - cmake --build . --config Release
  - ctest -VV
  - cmake --build . --config Release --target package

branches:
  only:
    - master

notifications:
  email: false

