language: cpp

os:
  - windows
  - linux
  - osx

dist: xenial

addons:
  apt:
    packages:
    - ocl-icd-opencl-dev

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .

branches:
  only:
    - master

notifications:
  email: false

