language: cpp

os:
  - windows
  - linux
  - osx

addons:
  apt:
    packages:
    - opencl-clhpp-headers
    - ocl-icd-opencl-dev

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .

install:
  - cmake --build . --target install

branches:
  only:
    - master

notifications:
  email: false
