language: cpp

matrix:
  include:
    - name: "Windows"
      os: windows
      env: CMAKE_GENERATOR_PLATFORM="x64"
    - name: "Linux"
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - ocl-icd-opencl-dev
    - name: "OSX"
      os: osx

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .

branches:
  only:
    - master

notifications:
  email: false

