name: clpeak
base: core20
adopt-info: clpeak
summary: Benchmarking tool to measure peak capabilities of opencl devices
description: |
  A synthetic benchmarking tool to measure peak capabilities of opencl devices.
  It only measures the peak metrics that can be achieved using vector operations and does not represent a real-world use case

grade: stable
confinement: classic

apps:
  clpeak:
    command: usr/local/bin/clpeak

parts:
  clpeak:
    source: .
    plugin: cmake
    build-packages:
      - build-essential
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "`grep 'VERSION_MAJOR ' cmake/common.cmake | awk -F'[() ]' '{print $3}'`.`grep 'VERSION_MINOR ' cmake/common.cmake | awk -F'[() ]' '{print $3}'`.`grep 'VERSION_PATCH ' cmake/common.cmake | awk -F'[() ]' '{print $3}'`"
